### ISSUE TITLE
top 3 reference file same as standard reference file

### ISSUE THREAD

**Issue by lpoorvin** [pirovc/ganon_benchmark#2]
When running the "generate reference files" section, the output file from the top 3 command line is identical to the output file of the non-top 3 command.  I'm using newly downloaded refseq sequences and a tab separated acc_len_taxid_assembly.txt file that consists of the RefSeq-Accn / Sequence-Length / Taxid / RefSeq Assembly Accession values from the updated_sequence_accession.txt file generated by genome_updater.  It looks like the top 3 command line:

1. takes the RefSeq Unit Accession values from assembly.txt
2. sorts the values
3. removes duplicates
4. uses the values as input to zcat
5. appends the decompressed seqs to the t3a.fna file

Is the acc_len_taxid_assembly.txt not directly from the genome_updater aux file?  Was there a previous filtering step I overlooked?

Sorry if I'm missing something obvious.  So far it looks like ganon is a great solution to get around centrifuge's resource hungry index generation, thanks for the hard work!

Leo

**Comment by pirovc** [comment]
Hi @lpoorvin 

Sorry for the late response, for some reason I was not notified in my email for this issue.

The commands on the README of this repository are made to recreate the exact same reference set as used in the manuscript evaluations. The command are doing exactly what you described, but the input provided there (`files/abfv_refseq_cg_t3a/20181219_abfv_refseq_cg_t3a_acc_len_taxid_assembly.txt`) is already filtered with the top 3 assemblies.

If I got it right you are trying to do the same procedure "top-3" for a newly generated file. If that is the case, to get the top 3 assemblies from acc_len_taxid_assembly.txt do the following, changing INFILE and TOP for your purposes:

`INFILE="files/abfv_refseq_cg/20181219_abfv_refseq_cg_acc_len_taxid_assembly.txt"`
`TOP="3"`
`join -1 1 -2 4 <(awk '{id=$3"-"$4; sumlen[id]+=$2;}END{for(s in sumlen){split(s,i,"-"); print i[1], i[2], sumlen[s]}}' ${INFILE} | sort -k 1,1 -k 3rn,3 | awk -v top=${TOP} '{if(taxid_cnt[$1]<top){print $2;taxid_cnt[$1]+=1}}' | sort) <(sort -k 4,4 ${INFILE}) -t$'\t' -o "2.1,2.2,2.3,2.4"`

Based on the files of this repository, this command will output the file `files/abfv_refseq_cg_t3a/20181219_abfv_refseq_cg_t3a_acc_len_taxid_assembly.txt`

Cheers
Vitor
